Does this work then?

diff --git a/SebastiaanSchool/bin/generate-constants b/SebastiaanSchool/bin/generate-constants
--- a/SebastiaanSchool/bin/generate-constants
+++ b/SebastiaanSchool/bin/generate-constants
@@ -11,6 +11,7 @@ set -x
 set -e
 
 if [ ! -f "${PROJECT_DIR}/bin/setEnv.sh" ]; then
+    echo "File not found!" 1>&2
     cp "${PROJECT_DIR}/bin/setEnv-Example.sh" "${PROJECT_DIR}/bin/setEnv.sh"
 fi
 
